pipeline:
  test:
    image: fnndsc/python-poetry
    commands:
    - poetry install
    - poetry run pytest -vvv
  pylint:
    image: cytopia/pylint
    commands:
    - find . -type f -name "*.py" | xargs pylint
