pipeline:
  pylint:
    image: fnndsc/python-poetry
    commands:
    - poetry add pylint
    - poetry install
    - find . -type f -name "*.py" | xargs poetry run pylint --disable=E0401
  flake8:
    image: fnndsc/python-poetry
    commands:
    - poetry add flake8
    - poetry install
    - poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
